export { default as Home } from './home/Home'
export { default as Categories } from './categories/Categories'
export { default as Favorites } from './favorites/Favorites'
export { default as Detail } from './detail/Detail'
export { default as NotFound } from './notfound/NotFound'